apiVersion: v1
kind: Pod
metadata:
  name: ci
  namespace: jenkins
spec:
  containers:
  - name: main
    image: harbor-ap1.zilliz.cc/devops/cd-base:20220316-a7c2c5e
    args: ["cat"]
    tty: true
  - name: kaniko
    imagePullPolicy: IfNotPresent
    image: harbor-ap1.zilliz.cc/devops/kaniko-executor:v1.8.0-debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker/
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
        items:
          - key: .dockerconfigjson
            path: config.json