basePath: /api/v1
host: localhost:7001
info:
  contact:
    email: xueyou@starboardventures.io
    name: xueyouchen
  description: starboard event tracing job
  termsOfService: http://swagger.io/terms/
  title: starboard fevm event tracing job
  version: "1.0"
paths:
  /deal-proposal-create-event-tracing-cron:
    post:
      consumes:
      - application/json
      - application/json
      description: deal-proposal-create's event cron job api, call by dolphin scheduler
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      tags:
      - Inner|Cron
  /pfil-event-tracing-cron:
    post:
      consumes:
      - application/json
      - application/json
      description: pfil's event cron job api, call by dolphin scheduler
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      tags:
      - Inner|Cron
  /ping:
    get:
      consumes:
      - application/json
      - application/json
      description: Healthy examination
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
        "500":
          description: error:...
          schema:
            type: string
      tags:
      - Sys
  /repl-auction-event-tracing-cron:
    post:
      consumes:
      - application/json
      - application/json
      description: replAuction's event cron job api, call by dolphin scheduler
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      tags:
      - Inner|Cron
  /repl-event-tracing-cron:
    post:
      consumes:
      - application/json
      - application/json
      description: repl's event cron job api, call by dolphin scheduler
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      tags:
      - Inner|Cron
  /wfil-event-tracing-cron:
    post:
      consumes:
      - application/json
      - application/json
      description: wfil's event cron job api, call by dolphin scheduler
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      tags:
      - Inner|Cron
swagger: "2.0"
